paths:
  /user/reviews:
    get:
      tags:
        - User
      summary: 내가 작성한 리뷰 목록 조회
      parameters:
        - name: userId
          in: query
          required: true
          schema:
            type: string
            description: 사용자 ID
            example: user123
        - name: page
          in: query
          required: true
          schema:
            type: integer
            description: 페이지 번호 (1 이상)
            example: 1
        - name: limit
          in: query
          required: true
          schema:
            type: integer
            description: 한 페이지당 리뷰 수
            example: 10
      responses:
        '200':
          description: 내가 작성한 리뷰 목록 조회 성공
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: string
                example: SUCCESS
              message:
                type: string
                example: 내가 작성한 리뷰 목록을 성공적으로 조회했습니다.
              data:
                type: array
                items:
                  type: object
                  properties:
                    storeName:
                      type: string
                      example: 가게 이름
                    reviewPhotos:
                      type: array
                      items:
                        type: string
                      example: ["https://example.com/photo1.jpg", "https://example.com/photo2.jpg"]
                    reviewPage:
                      type: object
                      properties:
                        nickname:
                          type: string
                          example: 사용자 닉네임
                        rating:
                          type: integer
                          example: 5
                        date:
                          type: string
                          example: 2024-07-05
                        content:
                          type: string
                          example: 리뷰 내용입니다.
                    reviewButton:
                      type: string
                      example: 리뷰 남기기 버튼
                    totalPages:
                      type: integer
                      example: 3
                    currentPage:
                      type: integer
                      example: 1
        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: string
                example: INVALID_REQUEST
              message:
                type: string
                example: 요청이 잘못되었습니다. 필수 매개변수를 확인하세요.
        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: string
                example: SERVER_ERROR
              message:
                type: string
                example: 서버에서 오류가 발생했습니다. 관리자에게 문의하세요.
