
paths:
  /{storeId}/reviews:
    get:
      tags:
        - Store
      summary: 가게 별 리뷰 조회 로직
      parameters:
        - name: storeId
          in: path
          schema:
            type: integer
          required: true
        - name: reviewId
          in: query
          required: false
          schema:
            properties:
              reviewId:
                type: integer
        - name: paging
          in: query
          required: true
          schema:
            properties:
              size:
                type: integer
      responses:
        '200':
          description: 리뷰 조회 성공
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: array
                example: {
                  "reviewData": [
                    {
                      "user_name": "SwaggerTest1",
                      "rate": 5,
                      "review_body": "리뷰1",
                      "create_date": "2000.01.01"
                    },
                    {
                      "user_name": "SwaggerTest2",
                      "rate": 4.5,
                      "review_body": "리뷰2",
                      "create_date": "2000.02.02"
                    }
                  ],
                  "cursorId": 1
                }
                
        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.


  /store/{storeId}/missions:
    get:
      tags:
        - Store
      summary: 특정 가게의 미션 목록 조회
      parameters:
        - name: storeId
          in: path
          required: true
          schema:
            type: string
          description: 조회할 가게의 ID
        - name: page
          in: query
          required: true
          schema:
            type: integer
            example: 1
          description: 페이지 번호
      responses:
        '200':
          description: 성공적으로 미션 목록 조회
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    missionId:
                      type: integer
                      description: 미션 ID
                    price:
                      type: integer
                      description: 음식 가격
                    points:
                      type: integer
                      description: 보상 포인트
                    status:
                      type: string
                      description: 미션 상태
                      example: "진행중"
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 잘못된 페이지 번호입니다.
        '500':
          description: 서버 에러
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 서버 에러, 관리자에게 문의 바랍니다.
